-- Keep source-specific anime metadata separate from the merged application catalog.

CREATE TABLE IF NOT EXISTS public.anime_source_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mal_id integer NOT NULL CHECK (mal_id > 0),
    source text NOT NULL CHECK (source IN ('anime_offline_database', 'jikan')),
    source_version text NOT NULL,
    source_url text NOT NULL,
    source_updated_at date,
    normalized_data jsonb NOT NULL CHECK (jsonb_typeof(normalized_data) = 'object'),
    imported_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (mal_id, source)
);

CREATE INDEX IF NOT EXISTS anime_source_records_source_mal_id_idx
    ON public.anime_source_records (source, mal_id);

ALTER TABLE public.anime_source_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anime source records: public can read ODbL" ON public.anime_source_records;
CREATE POLICY "anime source records: public can read ODbL"
    ON public.anime_source_records FOR SELECT
    TO anon, authenticated
    USING (source = 'anime_offline_database');

DROP POLICY IF EXISTS "anime source records: admins can read all" ON public.anime_source_records;
CREATE POLICY "anime source records: admins can read all"
    ON public.anime_source_records FOR SELECT
    TO authenticated
    USING (public.is_current_user_admin());

GRANT SELECT ON public.anime_source_records TO anon, authenticated;
GRANT ALL ON public.anime_source_records TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.anime_source_records_id_seq TO service_role;

COMMENT ON TABLE public.anime_source_records IS
    'Normalized source snapshots. ODbL rows are public; Jikan rows remain internal.';
COMMENT ON COLUMN public.anime_source_records.normalized_data IS
    'Source-specific normalized data before it is merged into public.anime.';
