-- 取り込んだカバー画像の出典台帳。anime.cover_url に載せた画像が「どこから・いつ・何を」
-- 取得したものかを残し、削除依頼や出典単位の一括取り下げに使う。
-- 書き込みは scripts/import-jikan-covers.ts（service_role）のみ。

CREATE TABLE IF NOT EXISTS public.anime_cover_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id bigint NOT NULL REFERENCES public.anime(id) ON DELETE CASCADE,
    mal_id integer CHECK (mal_id > 0),
    source text NOT NULL CHECK (source IN ('jikan')),
    -- 取得元の画像 URL（MAL CDN）と、それを得た API の URL
    source_image_url text NOT NULL,
    source_api_url text NOT NULL,
    -- anime-covers バケット直下のオブジェクト名（サムネイルは thumbs/160/ に同名で置く）
    object_name text NOT NULL UNIQUE,
    sha256 text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    source_width integer NOT NULL CHECK (source_width > 0),
    source_height integer NOT NULL CHECK (source_height > 0),
    width integer NOT NULL CHECK (width > 0),
    height integer NOT NULL CHECK (height > 0),
    bytes integer NOT NULL CHECK (bytes > 0),
    review_status text NOT NULL DEFAULT 'needs_review'
        CHECK (review_status IN ('approved', 'needs_review', 'rejected')),
    review_reason text,
    fetched_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (anime_id, source)
);

CREATE INDEX IF NOT EXISTS anime_cover_assets_review_status_idx
    ON public.anime_cover_assets (review_status, source);

ALTER TABLE public.anime_cover_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anime cover assets: admins can read" ON public.anime_cover_assets;
CREATE POLICY "anime cover assets: admins can read"
    ON public.anime_cover_assets FOR SELECT
    TO authenticated
    USING (public.is_current_user_admin());

GRANT SELECT ON public.anime_cover_assets TO authenticated;
GRANT ALL ON public.anime_cover_assets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.anime_cover_assets_id_seq TO service_role;

COMMENT ON TABLE public.anime_cover_assets IS
    'Provenance of imported anime cover images (source URL, hash, review state). Internal; admins can read.';
COMMENT ON COLUMN public.anime_cover_assets.review_status IS
    'approved: published to anime.cover_url / needs_review: held for an admin (unusual shape or size) / rejected: taken down.';
